# Site settings
title: "smcleod.net"
email: "blog(at)auto.smcleod.net"
description: "The blog of Sam McLeod"
baseurl: ""
url: ""
enable_retina: true
permalink: /:categories/:title/
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About / Contact', '/author/sam/', 'fa-anchor']
single_footer: '<p>Copyright Sam McLeod and Respective Authors</p>'
footer_links:
    About: ['About', '/author/sam/']
    Twitter : ['Twitter', 'https://twitter.com/s_mcleod']
    Github : ['Github', 'https://github.com/sammcj']
    LinkedIn : ['LinkedIn', 'https://linkedin.com/sammcj']

# Added by Sam
paginate: 10
plugins: [jekyll-paginate]
paginate_path: "/page:num"
author:
  name: Sam McLeod
  github: sammcj
  twitter: s_mcleod

disqus: "smcleodnet"
google_analytics: "UA-59178670-1"
excerpt_separator: "<!--more-->"
timezone: "Australia/Melbourne"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge