# Site
name: "smcleod.net"
description: "The blog of Sam McLeod"
meta_description: "The blog of Sam McLeod"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 100
baseurl: ""
excerpt_separator: "<!--more-->"
timezone: "Australia/Melbourne"

# Authors
authors:
  sam:
    name: Sam
    display_name: Sam
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: "blog(at)auto.smcleod.net"
    web: https://smcleod.net
    twitter: https://twitter.com/s_mcleod
    description: "I should write something here..."

# Social
twitter:
  username: s_mcleod
  card: summary

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-admin
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:categories/:title/'

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
