# Site
name: "smcleod.net"
description: "The blog of Sam McLeod"
meta_description: "The blog of Sam McLeod"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
baseurl: ""
disqus: "smcleodnet"
google_analytics: "UA-59178670-1"
excerpt_separator: "<!--more-->"
timezone: "Australia/Melbourne"
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sam:
    name: Sam
    display_name: Sam
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: "blog(at)auto.smcleod.net"
    web: https://smcleod.net
    twitter: https://twitter.com/s_mcleod
    description: "I should write something here..."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-admin

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:categories/:title/'

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
