# Site settings
title: smcleod.net
email: blog@auto.smcleod.net
description: The personal blog of Sam McLeod
baseurl: ""
url: ""
enable_retina: true
permalink: /:categories/:title/
nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/michelle', 'fa-user']
single_footer: '<p>&copy;</p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Writer 2016', '/about']

# Added by Sam
author:
  name: Sam McLeod
  github: sammcj
  twitter: s_mcleod

disqus: "smcleodnet"
google_analytics: "UA-59178670-1"
excerpt_separator: "<!--more-->"
timezone: "Australia/Melbourne"

# Build settings
# markdown: kramdown
