theme = "archie"
baseURL = "https://smcleod.net"
languageCode = "en-gb"
languageName = "English"
defaultContentLanguage = "en"
title = "smcleod.net"
copyright = "Sam McLeod"
timeZone = "Australia/Melbourne"

paginate = 100
summaryLength = 50
enableRobotsTXT = true
# relativeURLs = true

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true
enableEmoji = true
enableInlineShortcodes = true
newContentEditor = "code"
removePathAccents = true

[imaging]
anchor = 'Smart'
bgColor = '#ffffff'
hint = 'photo'
quality = 75
resampleFilter = 'Box'

[[menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
# pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
# post = ""
name = "📝 Posts"
url = "/posts/"
# title will be shown when you hover on this menu link
# title = ""
weight = 1
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "🍱 Categories"
url = "/categories/"
title = ""
weight = 3
[[menu.main]]
identifier = "series"
pre = ""
post = ""
name = "📚 Series"
url = "/series/"
title = ""
weight = 4
[[menu.main]]
identifier = "links"
pre = ""
post = ""
name = "🔗 Links"
url = "/links/"
title = "Links to software and services I use"
weight = 5
[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "🤦🏻‍♂️ About"
url = "/about/"
title = "Sam McLeod"
weight = 6
[[menu.main]]
identifier = "contact"
pre = ""
post = ""
name = "💬 Contact"
url = "/contact/"
title = "Contact me"
weight = 7

[permalinks]
posts = "/:year/:month/:slug/"
page = "/:slug/"

[params]
author = "Sam McLeod"
# subtitle = "The personal blog of Sam McLeod"

mode="light" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "push buttons, turn knobs, pull levers"
mathjax = true # enable MathJax support
katex = true # enable KaTeX support

highlightWrap = true
logo = "/logo-painted-350.svg"
favicon = "/favicon-128x128.png"
faviconIco = "/favicon.ico"
appletouch = "/favicon-256x256.png" # 180x180
# svgicon = "/logo-painted-350.svg"
icon512 = "/icon512.png" # 512x512 png

# version = "0.4.X"
fingerprint = "" # sha512
gitRepo = "https://github.com/sammcj/smcleod"
keywords = [
  "Sam McLeod",
  "sammcj",
  "smcleod",
  "s_mcleod",
  "DevOps",
  "Tech",
  "Engineering",
  "AI",
  "ML"
]
images = ["/logo-painted-350.svg"]

[params.home]
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
# gravatarEmail = "gravatar@auto.smcleod.net"
# URL of avatar shown in home page
avatarURL = "/logo-painted-350.svg"
images = ["/logo-painted-350.svg"]
title = "smcleod.net"
subtitle = "push buttons, turn knobs, pull levers"

[markup]
defaultMarkdownHandler = 'goldmark'

# Author config
[author]
name = "Sam McLeod"
link = "https://www.linkedin.com/in/sammcj/"
avatar = "/logo-painted-350.svg"
gravatarEmail = ""

# Sitemap config
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
posts = "/:year/:month/:title"
category = "/blog/category/:slug/"
#
# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
# privacy of the Google Analytics (replaced by params.analytics.google)
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# Options to make hugo output files
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

# Options for taxonomies
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"
